### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by mlknz** [jake-stewart/cpp-json#4]
Great lib, checked it with clang 15. 
However it is not clear from readme that there is no MSVC support.
I suggest adding it to readme if it is not planned to fix.
First issue is [using of case ranges](https://stackoverflow.com/questions/5924681/are-elipses-in-case-statements-standard-c-c).
However, after fixing them I found out that templates can't deduce their types either, so I stopped my attempt.
Checked with Visual Studio 2022, C++20 (latest).

**Comment by jake-stewart** [comment]
unfortunately i don't use windows so won't be able to help here

**Comment by mlknz** [comment]
I understand, suggestion: maybe it is worth adding this info to Readme?

**Comment by jake-stewart** [comment]
sure

**Comment by jake-stewart** [comment]
i don't mind leaving this issue open as lack of MSVC support should be considered a bug
